### PR TITLE
examples: drop redundant imports and libs

### PR DESCRIPTION
**Pull request by juhp**
Just some trivial simplifications to the examples - nothing interesting.

Thanks for making this project - it's really useful!

### CODE REVIEW

**Comment by juhp** [comment]
Btw it builds fine with lean 4.13.0 - I could also update the toolchain if you wish

**Comment by juhp** [comment]
Btw I am using it in my first small library: https://github.com/juhp/curl-json-lean

**Comment by bergmannjg** [comment]
Thanks!

> Btw it builds fine with lean 4.13.0 - I could also update the toolchain if you wish

This would be great.

**Comment by juhp** [comment]
(Maybe some of curljson could be merged into this library eventually)

**Comment by juhp** [comment]
Added the toolchain bump here - hope that's okay

**Comment by bergmannjg** [comment]
> Maybe some of curljson could be merged into this library eventually

Please add your code in a new pr.
What do you think about building a corresponding Xml workflow?

**Pull request merged**
